spring.application.name=moderation-service
server.port=8088
eureka.client.service-url.defaultZone=http://localhost:8083/eureka/
eureka.instance.prefer-ip-address=true
moderation.gemini.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# VÉRIFIEZ : Assurez-vous que cette ligne est présente et contient votre clé API valide
google.api.key=AIzaSyCCheZaU2_oUJLlsVpfiov6RMsbQu3sVPc 

spring.main.lazy-initialization=true
spring.main.banner-mode=off
spring.jmx.enabled=false
server.tomcat.max-threads=50